In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
# 파일 불러오기
wed = pd.read_csv('weather/OBS_AWS_DD_20250729121458.csv', encoding='cp949')
rain = pd.read_csv('weather/서울시_강우량_정보_2024년12월.csv', encoding='cp949')
pol = pd.read_csv('weather/일별평균대기오염도_2024.csv', encoding='cp949')

In [58]:
print(wed.head())
print(rain.head())
print(pol.head())

    지점 지점명          일시  평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)
0  400  강남  2024-01-01       3.7      -0.9       7.1       0.0
1  400  강남  2024-01-02       3.6       1.6       4.8       0.0
2  400  강남  2024-01-03       2.2       0.5       5.0       0.5
3  400  강남  2024-01-04       2.0      -2.6       5.3       0.0
4  400  강남  2024-01-05       5.5       2.2      10.2       0.0
   강우량계 코드 강우량계명  구청 코드  구청명  10분우량           자료수집 시각
0      101  강남구청    101  강남구    0.0  2024-12-02 15:39
1      102   세곡동    101  강남구    0.0  2024-12-02 15:39
2      201  강동구청    102  강동구    0.0  2024-12-02 15:39
3      402  상계1동    104  노원구    0.0  2024-12-02 15:39
4      901  성동구청    109  성동구    0.0  2024-12-02 15:39
       측정일시  측정소명  이산화질소농도(ppm)  오존농도(ppm)  일산화탄소농도(ppm)  아황산가스농도(ppm)  \
0  20240101   강남구        0.0280     0.0130          0.65        0.0028
1  20240101  강남대로        0.0269     0.0106          1.27        0.0031
2  20240101   강동구        0.0305     0.0116          0.92        0.0020
3  20240101  강변북로        0.0325     0.0081          0.46        0.0025
4  20240101   강북구        0.0243     0.0157          0.71        0.0025

   미세먼지농도(㎍/㎥)  초미세먼지농도(㎍/㎥)
0         23.0          18.0
1         28.0          24.0
2         20.0          15.0
3         26.0          23.0
4         19.0          15.0

In [8]:
# nunique 확인
def uni_df(dataframe):
    for col in dataframe:
        print(col,dataframe[col].unique())
        print(col,dataframe[col].nunique())

In [19]:
uni_df(pol)

측정일시 [20240101 20240102 20240103 20240104 20240105 20240106 20240107 20240108
 20240109 20240110 20240111 20240112 20240113 20240114 20240115 20240116
 20240117 20240118 20240119 20240120 20240121 20240122 20240123 20240124
 20240125 20240126 20240127 20240128 20240129 20240130 20240131 20240201
 20240202 20240203 20240204 20240205 20240206 20240207 20240208 20240211
 20240212 20240213 20240214 20240215 20240216 20240217 20240218 20240219
 20240220 20240221 20240222 20240223 20240224 20240225 20240226 20240227
 20240228 20240229 20240301 20240302 20240303 20240304 20240305 20240306
 20240307 20240308 20240309 20240310 20240311 20240312 20240313 20240314
 20240315 20240316 20240317 20240318 20240319 20240320 20240321 20240322
 20240323 20240324 20240325 20240326 20240327 20240328 20240329 20240330
 20240331 20240401 20240402 20240403 20240404 20240405 20240406 20240407
 20240408 20240409 20240410 20240411 20240412 20240413 20240414 20240415
 20240416 20240417 20240418 20240419 20240420 20240421 20240422 20240423
 20240424 20240425 20240426 20240427 20240428 20240429 20240430 20240501
 20240502 20240503 20240504 20240505 20240506 20240507 20240508 20240509
 20240510 20240511 20240512 20240513 20240514 20240515 20240516 20240517
 20240518 20240519 20240520 20240521 20240522 20240523 20240524 20240525
 20240526 20240527 20240528 20240529 20240530 20240531 20240601 20240602
 20240603 20240604 20240605 20240606 20240607 20240608 20240609 20240610
 20240611 20240612 20240613 20240614 20240615 20240616 20240617 20240618
 20240619 20240620 20240621 20240622 20240623 20240624 20240625 20240626
 20240627 20240628 20240629 20240630 20240701 20240702 20240703 20240704
 20240705 20240706 20240707 20240708 20240709 20240710 20240711 20240712
 20240713 20240714 20240715 20240716 20240717 20240718 20240719 20240720
 20240721 20240722 20240723 20240724 20240725 20240726 20240727 20240728
 20240729 20240730 20240731 20240801 20240802 20240803 20240804 20240805
 20240806 20240807 20240808 20240809 20240810 20240811 20240812 20240813
 20240814 20240815 20240816 20240817 20240818 20240819 20240820 20240821
 20240822 20240823 20240824 20240825 20240826 20240827 20240828 20240829
 20240830 20240831 20240901 20240902 20240903 20240904 20240905 20240906
 20240907 20240908 20240909 20240910 20240911 20240912 20240913 20240914
 20240915 20240916 20240917 20240918 20240919 20240920 20240921 20240922
 20240923 20240924 20240925 20240926 20240927 20240928 20240929 20240930
 20241001 20241002 20241003 20241004 20241005 20241006 20241007 20241008
 20241009 20241010 20241011 20241012 20241013 20241014 20241015 20241016
 20241017 20241018 20241019 20241020 20241021 20241022 20241023 20241024
 20241025 20241026 20241027 20241028 20241029 20241030 20241031 20241101
 20241102 20241103 20241104 20241105 20241106 20241107 20241108 20241109
 20241110 20241111 20241112 20241113 20241114 20241115 20241116 20241117
 20241118 20241119 20241120 20241121 20241122 20241123 20241124 20241125
 20241126 20241127 20241128 20241129 20241130 20241201 20241202 20241203
 20241204 20241205 20241206 20241207 20241208 20241209 20241210 20241211
 20241212 20241213 20241214 20241215 20241216 20241217 20241218 20241219
 20241220 20241221 20241222 20241223 20241224 20241225 20241226 20241227
 20241228 20241229 20241230 20241231]
측정일시 364
측정소명 ['강남구' '강남대로' '강동구' '강변북로' '강북구' '강서구' '공항대로' '관악구' '관악산' '광진구' '구로구'
 '금천구' '남산' '노원구' '도봉구' '도산대로' '동대문구' '동작구' '동작대로' '마포구' '마포아트센터' '북한산'
 '서대문구' '서울숲' '서초구' '성동구' '성북구' '세곡' '송파구' '시흥대로' '신촌로' '양천구' '영등포구'
 '영등포로' '올림픽공원' '용산구' '은평구' '자연사박물관' '정릉로' '종로' '종로구' '중구' '중랑구' '천호대로'
 '청계천로' '한강대로' '항동' '행주' '홍릉로' '화랑로']
측정소명 50
이산화질소농도(ppm) [0.028  0.0269 0.0305 0.0325 0.0243 0.0354 0.0311 0.0332 0.0073 0.033
 0.0218 0.0324 0.0268 0.0281 0.027  0.026  0.0301 0.0323 0.0373 0.0345
 0.0289 0.0092 0.0252 0.0288 0.0262 0.0224 0.03   0.0355 0.0314 0.0353
 0.0239 0.0246 0.0251 0.0364 0.0271 0.0278 0.0304 0.0318 0.0327 0.0294
 0.0241 0.0297 0.0303 0.0133 0.0249 0.0309 0.0147 0.0282 0.0171 0.0164
 0.0196 0.013  0.0244 0.0395 0.0201 0.0064 0.0212 0.0195 0.0199 0.0223
 0.0184 0.0285 0.0274 0.0348 0.0299 0.0204 0.0219 0.0194 0.0208 0.0371
 0.0176 0.0193 0.0207 0.0339 0.023  0.0256 0.0293 0.0336 0.0341 0.0399
 0.036  0.0182 0.0362 0.0296 0.0154 0.0434 0.0225 0.0389 0.0229 0.0291
 0.0254 0.0264 0.0295 0.04   0.0088 0.0287 0.0322 0.0255 0.032  0.0377
 0.0367 0.0333 0.0351 0.0313 0.0272 0.0232 0.0234 0.0386 0.0205 0.0238
 0.0236 0.041  0.0321 0.0375 0.0388 0.0398 0.0308 0.0408 0.0242 0.0337
 0.0334 0.0372 0.0359 0.0391 0.0347 0.0433 0.0338 0.0306 0.0361 0.037
 0.0425 0.034  0.0374 0.0263 0.0478 0.0404 0.035  0.0378 0.0298 0.0379
 0.0409 0.0411 0.042  0.014  0.0221 0.0315 0.0317 0.0363 0.0406 0.0369
 0.0279 0.0344 0.0267 0.029  0.0487 0.0328 0.0393 0.0423 0.0402 0.0192
 0.0261 0.0136 0.0206 0.0105 0.0127 0.019  0.0177 0.0214 0.0166 0.0072
 0.017  0.0148 0.0172 0.022  0.025  0.0174 0.0152 0.0156 0.0312 0.0155
 0.0161 0.0215 0.0186 0.0122 0.0276 0.0102 0.0126 0.0119 0.0059 0.0131
 0.012  0.0056 0.0108 0.0086 0.0112 0.0106 0.0095 0.0061 0.0114 0.0109
 0.0116 0.0132 0.0104 0.0053 0.009  0.0074 0.0089 0.006  0.01   0.0123
 0.0167 0.0153 0.0111 0.0101 0.0091 0.0094 0.0125 0.0146 0.0096 0.0141
 0.0068 0.0042 0.0151 0.0149 0.0277 0.024  0.0143 0.0259 0.0248 0.0275
 0.0231 0.031  0.0233 0.0397 0.0417 0.0442 0.0449 0.0416 0.0441 0.0054
 0.0471 0.0307 0.0352 0.043  0.0432 0.0401 0.0426 0.0403 0.0422 0.0431
 0.0394 0.0475 0.0444 0.0414 0.0493 0.0407 0.0424 0.0383 0.0413 0.046
 0.0331 0.0509 0.0412 0.0384 0.045  0.0429 0.0486 0.0335 0.0356 0.0368
 0.0455 0.0418 0.0178 0.039  0.0357 0.0385 0.0319 0.0437 0.048  0.0458
 0.0346 0.0472 0.0435 0.0366 0.0419 0.0474 0.0443 0.0405 0.0495 0.0439
 0.0381 0.0464 0.0421 0.0302 0.0446 0.0448 0.0453 0.0466 0.0427 0.0157
 0.0138 0.0237 0.0197 0.0185 0.0145 0.0316 0.0343 0.0365 0.0115 0.0358
 0.0245 0.0284 0.0265 0.0286 0.0387 0.0415 0.0454 0.0376 0.0382 0.0445
 0.0342 0.0203 0.0181 0.0159 0.0135 0.0117 0.0189 0.0162 0.0222 0.0179
 0.0165 0.0142 0.0057 0.0273 0.0326 0.047  0.0438 0.038  0.0547 0.0484
 0.05   0.004  0.051  0.0492 0.0496 0.0546 0.0504 0.058  0.0564 0.0479
 0.0436 0.0523 0.0462 0.0467 0.0482 0.0069 0.0247 0.0283 0.0113 0.0257
 0.0253 0.0169 0.0258 0.007  0.016  0.0183 0.0202 0.0173 0.0124 0.0098
 0.0191 0.0099 0.015  0.0049 0.0103 0.0082 0.0045 0.0039 0.0107 0.0084
 0.0087 0.0266 0.0158 0.0058 0.0063 0.0093 0.0085 0.0198 0.0129 0.0144
 0.0078 0.0043 0.0226 0.02   0.0097 0.0065 0.0118 0.0051 0.0083 0.0137
 0.011  0.0047 0.0028 0.0188 0.0128 0.0076 0.008  0.0216 0.0139 0.021
 0.0134 0.0031 0.0349 0.044  0.0468 0.0459 0.0175 0.0217 0.0292 0.0228
 0.0481 0.0505 0.0329 0.0506 0.0428 0.0461 0.0499 0.0465 0.0527 0.0525
 0.0526 0.0469 0.0516 0.0606 0.0537 0.0497 0.0604 0.0558 0.0511 0.0529
 0.066  0.0491 0.0528 0.0519 0.0488 0.0533 0.0599 0.0507 0.0562 0.0531
 0.0524 0.0639 0.0463 0.0489 0.0552 0.0168 0.0451 0.0392 0.0209 0.0211
 0.0163 0.0081 0.0121 0.0077 0.0235 0.0187 0.0227 0.0071 0.018  0.0066
 0.0396 0.0503 0.0662 0.0476 0.0494 0.0616 0.0447 0.0079 0.0213 0.0477
 0.0044 0.0075 0.0034 0.0055 0.0067    nan 0.0038 0.0033 0.0046 0.0023
 0.0483 0.0062 0.0456 0.0502 0.0457 0.005  0.0565 0.0452 0.049  0.0512
 0.0473 0.0522 0.057  0.0008 0.0052 0.0036 0.0048 0.0041 0.0534 0.053
 0.0027 0.0014 0.055  0.0013 0.0011 0.0037 0.002  0.0035 0.0016 0.003
 0.0022 0.0026 0.0029 0.0021 0.0032 0.0582 0.0579 0.052  0.0578 0.0555
 0.0508 0.0559 0.0514 0.0538 0.0605 0.054  0.    ]
이산화질소농도(ppm) 536
오존농도(ppm) [1.300e-02 1.060e-02 1.160e-02 8.100e-03 1.570e-02 1.230e-02 1.050e-02
 1.150e-02 3.690e-02 1.330e-02 1.020e-02 1.170e-02 1.830e-02 1.320e-02
 1.690e-02 1.010e-02 1.370e-02 1.290e-02 1.100e-02 1.600e-02 2.640e-02
 1.650e-02 1.140e-02 1.380e-02 9.500e-03 9.300e-03 1.510e-02 9.700e-03
 1.080e-02 1.250e-02 1.390e-02 1.870e-02 1.030e-02 1.480e-02 1.260e-02
 8.800e-03 1.240e-02 1.090e-02 1.270e-02 1.110e-02 9.100e-03 2.370e-02
 1.840e-02 1.660e-02 2.960e-02 2.260e-02 1.420e-02 2.130e-02 3.190e-02
 2.330e-02 1.720e-02 1.530e-02 2.770e-02 2.440e-02 3.360e-02 1.630e-02
 2.580e-02 1.790e-02 1.490e-02 2.020e-02 2.650e-02 3.250e-02 2.250e-02
 2.110e-02 2.240e-02 2.350e-02 9.900e-03 2.150e-02 1.470e-02 2.050e-02
 2.340e-02 2.310e-02 1.950e-02 2.420e-02 2.520e-02 2.590e-02 2.100e-02
 1.590e-02 2.210e-02 1.890e-02 1.340e-02 7.800e-03 8.700e-03 2.320e-02
 1.700e-02 3.120e-02 9.600e-03 2.460e-02 1.460e-02 1.550e-02 2.990e-02
 1.200e-02 6.900e-03 8.600e-03 1.190e-02 1.610e-02 1.880e-02 1.710e-02
 2.280e-02 2.270e-02 1.440e-02 6.400e-03 1.810e-02 1.780e-02 1.360e-02
 7.600e-03 8.900e-03 9.400e-03 1.210e-02 1.770e-02 4.160e-02 1.000e-02
 1.220e-02 1.930e-02 1.130e-02 1.760e-02 1.620e-02 6.700e-03 9.000e-03
 1.310e-02 1.670e-02 4.200e-03 2.570e-02 2.010e-02 2.600e-02 4.670e-02
 3.210e-02 2.120e-02 2.910e-02 2.180e-02 2.200e-02 3.200e-02 2.660e-02
 2.410e-02 2.840e-02 2.810e-02 2.170e-02 2.380e-02 1.750e-02 2.140e-02
 2.040e-02 2.430e-02 2.360e-02 2.800e-02 2.000e-02 1.800e-02 2.470e-02
 2.700e-02 1.040e-02 1.680e-02 2.070e-02 1.640e-02 2.820e-02 3.330e-02
 2.670e-02 3.240e-02 2.530e-02 1.940e-02 2.290e-02 2.710e-02 3.290e-02
 2.300e-02 2.400e-02 1.970e-02 2.480e-02 1.740e-02 2.750e-02 3.060e-02
 2.560e-02 2.510e-02 2.690e-02 2.720e-02 2.680e-02 2.550e-02 2.830e-02
 3.110e-02 2.760e-02 2.740e-02 2.850e-02 2.230e-02 2.860e-02 2.900e-02
 2.490e-02 1.400e-02 1.560e-02 1.350e-02 1.180e-02 1.280e-02 1.730e-02
 1.540e-02 1.070e-02 9.200e-03 3.100e-03 5.600e-03 3.000e-03 3.200e-03
 1.700e-03 4.100e-03 3.600e-03 3.800e-03 6.200e-03 3.500e-03 4.800e-03
 2.600e-03 3.700e-03 5.400e-03 1.900e-03 3.400e-03 4.700e-03 5.100e-03
 2.300e-03 4.600e-03 2.700e-03 2.800e-03 2.900e-03 4.500e-03 2.200e-03
 2.500e-03 4.400e-03 2.400e-03 6.600e-03 6.300e-03 5.000e-03 7.000e-03
 5.500e-03 6.000e-03 8.000e-03 8.200e-03 7.100e-03 6.100e-03 5.300e-03
 5.700e-03 6.500e-03 8.300e-03 3.900e-03 5.800e-03 7.300e-03 4.900e-03
 8.500e-03 4.300e-03 7.700e-03 1.430e-02 3.390e-02 5.900e-03 7.500e-03
 1.860e-02 7.400e-03 8.400e-03 7.200e-03 7.900e-03 3.070e-02 1.980e-02
 3.470e-02 2.620e-02 3.430e-02 2.450e-02 1.900e-02 3.440e-02 2.190e-02
 2.080e-02 2.060e-02 2.220e-02 3.400e-02 1.500e-02 1.580e-02 1.120e-02
 1.520e-02 3.890e-02 2.030e-02 6.800e-03 3.100e-02 2.880e-02 3.180e-02
 2.390e-02 3.410e-02 1.410e-02 2.100e-03 2.000e-03 4.530e-02 1.400e-03
 6.000e-04 1.600e-03 4.080e-02 2.730e-02 3.030e-02 3.510e-02 3.080e-02
 3.960e-02 2.870e-02 3.220e-02 3.090e-02 2.940e-02 3.370e-02 3.830e-02
 3.280e-02 3.340e-02 3.140e-02 2.930e-02 2.890e-02 3.150e-02 3.300e-02
 3.310e-02 3.260e-02 2.790e-02 3.170e-02 3.590e-02 3.520e-02 3.480e-02
 3.230e-02 3.760e-02 3.050e-02 3.790e-02 3.420e-02 3.000e-02 3.540e-02
 2.610e-02 1.850e-02 2.630e-02 2.920e-02 3.500e-02 2.980e-02 2.500e-02
 2.540e-02 3.040e-02 3.550e-02 3.320e-02 3.010e-02 3.600e-02 3.020e-02
 3.580e-02 3.490e-02 3.700e-02 3.620e-02 2.780e-02 2.950e-02 5.200e-03
 3.160e-02 1.960e-02 1.990e-02 2.970e-02 2.160e-02 3.940e-02 4.260e-02
 3.710e-02 1.820e-02 1.920e-02 4.240e-02 2.090e-02 1.910e-02 4.280e-02
 1.450e-02 3.350e-02 4.470e-02 3.910e-02 3.570e-02 3.130e-02 4.050e-02
 3.460e-02 9.800e-03 3.450e-02 4.060e-02 3.630e-02 3.840e-02 3.950e-02
 3.920e-02 3.670e-02 3.640e-02 3.660e-02 4.170e-02 3.380e-02 4.490e-02
 3.730e-02 5.230e-02 3.530e-02 3.870e-02 3.770e-02 4.300e-02 3.270e-02
 3.780e-02 3.720e-02 5.430e-02 6.240e-02 4.740e-02 4.590e-02 4.150e-02
 3.810e-02 4.410e-02 4.890e-02 4.070e-02 3.800e-02 4.810e-02 4.600e-02
 3.860e-02 4.230e-02 3.610e-02 4.180e-02 3.850e-02 3.650e-02 3.820e-02
 4.220e-02 3.560e-02 4.020e-02 4.120e-02 4.340e-02 5.010e-02       nan
 4.190e-02 3.990e-02 4.090e-02 4.720e-02 4.440e-02 3.750e-02 4.030e-02
 3.880e-02 4.010e-02 4.000e-02 4.210e-02 4.100e-02 3.900e-02 4.140e-02
 3.930e-02 3.970e-02 4.800e-02 3.680e-02 3.740e-02 4.610e-02 4.270e-02
 5.170e-02 4.660e-02 4.420e-02 4.460e-02 4.820e-02 4.250e-02 3.980e-02
 4.110e-02 4.450e-02 5.140e-02 4.130e-02 5.370e-02 4.290e-02 5.610e-02
 4.320e-02 5.710e-02 4.690e-02 4.650e-02 4.430e-02 4.570e-02 6.280e-02
 4.940e-02 4.780e-02 4.630e-02 6.320e-02 5.040e-02 4.480e-02 4.350e-02
 5.630e-02 4.900e-02 6.490e-02 4.500e-02 4.950e-02 4.910e-02 4.390e-02
 6.670e-02 4.620e-02 4.580e-02 5.300e-02 4.920e-02 4.330e-02 4.560e-02
 4.310e-02 4.200e-02 5.050e-02 4.760e-02 4.380e-02 4.040e-02 4.370e-02
 4.730e-02 4.700e-02 5.020e-02 5.260e-02 5.110e-02 5.690e-02 6.040e-02
 5.340e-02 4.750e-02 6.150e-02 4.990e-02 5.080e-02 4.840e-02 5.640e-02
 5.520e-02 4.520e-02 5.160e-02 5.360e-02 4.360e-02 4.830e-02 5.030e-02
 4.680e-02 4.400e-02 5.800e-02 4.510e-02 5.350e-02 5.060e-02 5.850e-02
 5.000e-02 7.750e-02 6.030e-02 5.450e-02 5.590e-02 5.130e-02 4.880e-02
 4.790e-02 4.930e-02 4.850e-02 4.550e-02 5.790e-02 5.200e-02 6.080e-02
 4.710e-02 5.420e-02 5.290e-02 5.680e-02 4.860e-02 4.640e-02 4.770e-02
 4.960e-02 7.500e-02 5.180e-02 5.880e-02 8.240e-02 5.250e-02 4.870e-02
 5.750e-02 5.600e-02 5.330e-02 6.050e-02 5.150e-02 5.100e-02 5.310e-02
 7.160e-02 6.130e-02 5.380e-02 5.730e-02 5.240e-02 5.220e-02 4.980e-02
 5.400e-02 5.070e-02 4.540e-02 5.700e-02 6.310e-02 6.630e-02 7.790e-02
 5.650e-02 5.970e-02 4.970e-02 5.770e-02 1.138e-01 5.270e-02 3.583e-01
 6.730e-02 6.680e-02 6.710e-02 6.370e-02 6.350e-02 1.070e-01 5.540e-02
 6.000e-02 7.370e-02 6.070e-02 9.200e-02 6.390e-02 7.010e-02 6.880e-02
 6.500e-02 6.700e-02 5.990e-02 5.780e-02 7.070e-02 6.620e-02 5.490e-02
 5.980e-02 6.120e-02 5.090e-02 5.480e-02 6.360e-02 5.760e-02 5.410e-02
 7.600e-02 5.190e-02 5.830e-02 5.550e-02 5.960e-02 5.320e-02 5.570e-02
 5.660e-02 5.580e-02 5.500e-02 5.840e-02 5.560e-02 5.460e-02 5.510e-02
 5.440e-02 5.870e-02 5.470e-02 7.240e-02 7.310e-02 7.580e-02 5.720e-02
 5.210e-02 5.810e-02 1.000e-04 8.200e-02 6.010e-02 5.390e-02 5.940e-02
 5.860e-02 5.120e-02 6.160e-02 7.060e-02 6.520e-02 6.220e-02 6.140e-02
 5.620e-02 6.330e-02 8.650e-02 7.850e-02 5.280e-02 7.650e-02 7.840e-02
 6.530e-02 7.280e-02 1.050e-01 6.860e-02 7.100e-02 6.790e-02 7.290e-02
 6.910e-02 6.930e-02 7.150e-02 5.820e-02 6.900e-02 6.450e-02 7.930e-02
 7.020e-02 6.660e-02 6.570e-02 6.020e-02 6.540e-02 6.840e-02 5.670e-02
 6.780e-02 6.250e-02 6.980e-02 6.420e-02 6.100e-02 6.760e-02 5.530e-02
 6.200e-02 7.110e-02 5.930e-02 6.380e-02 7.880e-02 6.340e-02 8.400e-02
 6.640e-02 6.290e-02 6.440e-02 6.270e-02 6.210e-02 6.690e-02 6.060e-02
 6.090e-02 7.660e-02 6.110e-02 6.300e-02 5.740e-02 7.560e-02 6.510e-02
 8.130e-02 7.200e-02 5.910e-02 6.550e-02 5.900e-02 5.890e-02 6.770e-02
 6.890e-02 5.920e-02 8.100e-02 6.810e-02 7.700e-02 8.090e-02 6.460e-02
 6.940e-02 1.002e-01 7.920e-02 7.210e-02 6.400e-02 7.900e-02 7.320e-02
 8.060e-02 7.260e-02 8.000e-02 6.560e-02 7.120e-02 7.810e-02 8.150e-02
 1.029e-01 9.740e-02 7.940e-02 8.560e-02 8.040e-02 9.720e-02 9.540e-02
 9.620e-02 7.620e-02 8.890e-02 8.710e-02 9.190e-02 8.680e-02 8.340e-02
 9.800e-02 8.440e-02 1.034e-01 8.730e-02 8.260e-02 8.570e-02 8.270e-02
 8.780e-02 8.290e-02 7.430e-02 1.012e-01 8.170e-02 8.660e-02 7.590e-02
 7.720e-02 7.250e-02 8.590e-02 9.080e-02 8.160e-02 9.220e-02 7.270e-02
 7.000e-02 6.990e-02 6.470e-02 6.870e-02 5.950e-02 7.540e-02 7.630e-02
 7.300e-02 6.410e-02 6.230e-02 7.710e-02 9.490e-02 8.760e-02 7.770e-02
 1.263e-01 9.910e-02 8.010e-02 9.060e-02 8.550e-02 9.630e-02 8.370e-02
 8.350e-02 9.400e-02 9.040e-02 9.150e-02 8.360e-02 7.140e-02 9.120e-02
 8.470e-02 9.270e-02 6.480e-02 6.580e-02 6.800e-02 8.460e-02 7.490e-02
 7.360e-02 8.220e-02 7.800e-02 9.230e-02 9.010e-02 9.140e-02 8.830e-02
 8.820e-02 1.021e-01 1.004e-01 8.770e-02 7.510e-02 9.410e-02 9.520e-02
 9.840e-02 7.550e-02 8.500e-02 8.740e-02 6.610e-02 8.190e-02 9.760e-02
 9.000e-02 8.920e-02 7.330e-02 9.820e-02 8.750e-02 7.780e-02 6.720e-02
 7.190e-02 7.980e-02 9.510e-02 7.970e-02 6.960e-02 7.220e-02 6.820e-02
 6.830e-02 6.180e-02 7.640e-02 6.650e-02 6.260e-02 6.970e-02 8.810e-02
 8.380e-02 7.460e-02 1.053e-01 9.170e-02 8.250e-02 8.050e-02 8.080e-02
 7.380e-02 8.480e-02 7.950e-02 7.040e-02 7.470e-02 6.850e-02 7.440e-02
 7.030e-02 7.530e-02 7.390e-02 6.190e-02 6.950e-02 8.410e-02 7.910e-02
 8.330e-02 8.180e-02 7.050e-02 8.510e-02 7.170e-02 8.230e-02 6.170e-02
 7.610e-02 6.590e-02 7.080e-02 8.110e-02 7.350e-02 8.210e-02 7.090e-02
 7.180e-02 8.320e-02 6.600e-02 8.300e-02 8.840e-02 9.640e-02 6.750e-02
 9.100e-02 6.920e-02 9.310e-02 6.430e-02 7.740e-02 4.000e-03 3.300e-03
 5.000e-04]
오존농도(ppm) 868
일산화탄소농도(ppm) [6.5000e-01 1.2700e+00 9.2000e-01 4.6000e-01 7.1000e-01 7.8000e-01
 8.7000e-01 2.2041e+02 7.9000e-01 6.9000e-01 8.9000e-01 8.8000e-01
 7.5000e-01 8.5000e-01 8.6000e-01 8.1000e-01 7.6000e-01 3.9000e-01
 1.0400e+00 1.0000e+00 6.8000e-01 6.6000e-01 1.1600e+00 8.3000e-01
 9.5000e-01 1.1300e+00 8.0000e-01 7.7000e-01 7.2000e-01 7.0000e-01
 9.4000e-01 7.4000e-01 4.7000e-01 8.4000e-01 3.3000e-01 4.8000e-01
 5.2000e-01 5.3000e-01 5.5000e-01 2.2997e+02 6.4000e-01 5.7000e-01
 7.3000e-01 4.9000e-01 5.1000e-01 6.2000e-01 3.4000e-01 9.1000e-01
 4.4000e-01 5.8000e-01 9.9000e-01 5.6000e-01 5.0000e-01 6.0000e-01
 6.3000e-01 1.4000e-01 5.9000e-01 6.1000e-01 4.3000e-01 9.0000e-01
 5.4000e-01 9.8000e-01 6.7000e-01 1.0300e+00 4.0000e-01 9.3000e-01
 1.0700e+00 1.1000e+00 1.0500e+00 8.2000e-01 1.1700e+00 1.0600e+00
 1.2800e+00 3.8000e-01 4.1000e-01 2.5000e-01 2.7000e-01 4.5000e-01
 3.6000e-01 4.2000e-01 2.4000e-01 3.5000e-01 2.9000e-01 3.1000e-01
 1.0900e+00 1.0800e+00 1.1200e+00 1.0100e+00 1.1100e+00 1.3000e-01
 3.2000e-01 2.2000e-01 3.7000e-01 2.8000e-01 2.3000e-01 1.0200e+00
 9.7000e-01 3.0000e-01 2.6000e-01 2.0000e-01 9.6000e-01 1.1400e+00
 1.2400e+00 1.5000e+00 2.1000e-01 1.1800e+00 1.0000e-02 1.7000e-01
        nan 1.6000e-01 1.5000e-01 1.8000e-01 1.9000e-01 3.0000e-02
 1.1000e-01 1.0000e-01 1.2000e-01 4.0000e-02 5.0000e-02 7.0000e-02
 8.0000e-02 9.0000e-02 2.0000e-02 1.2000e+00 1.1500e+00]
일산화탄소농도(ppm) 124
아황산가스농도(ppm) [0.0028 0.0031 0.002  0.0025 0.0033 0.0032 0.0027 0.0026 0.003  0.0029
 0.0037 0.0024 0.0022 0.0023 0.0039 0.0035 0.0021 0.0036 0.0034 0.0051
 0.0042 0.0038 0.0043 0.0044 0.0041 0.004  0.005  0.0045 0.0064 0.0046
 0.0048 0.0019 0.0018 0.0017 0.0016 0.0063 0.0059 0.0056 0.0068 0.0052
 0.0047 0.0049 0.0015    nan 0.0057 0.0053 0.0074 0.0014 0.0061 0.0055
 0.0058 0.0054 0.0013 0.0086 0.0009 0.001  0.0011 0.0012 0.0075 0.0066
 0.006  0.0008 0.0001]
아황산가스농도(ppm) 62
미세먼지농도(㎍/㎥) [ 23.  28.  20.  26.  19.  29.  25.  33.  18.  30.  24.  27.  14.  21.
  22.  32.  42.  46.  38.  35.  44.  45.  41.  34.  43.  39.  40.  36.
  48.  49.  37.  47.  31.  53.  56.  54.  52.  51.  58.  50.  57.  55.
  61.  83.  87.  85.  92.  82.  86.  73.  93.  79.  75.  77.  96.  84.
  80.  94.  74.  88.  81.  78.  91.  89.  76.  72.  17.  nan  10.  68.
  71.  65.  64.  67.  63.  69.  70.  59.  62.  66.  60.  16.  13.  15.
   8.  12.  11.   5.   3.   7.   4.   6.   9.  97.  90.  95. 112. 123.
 120. 127. 119. 101. 129. 114. 116. 113. 126. 118. 104. 121. 115. 109.
 105. 122. 111. 117. 110.  98. 106. 107. 108. 130. 144. 128. 103. 236.
 264. 290. 275. 265. 230. 195. 242. 327. 260. 261. 217. 248. 281. 276.
 279. 243. 219. 233. 267. 246. 285. 241. 266. 283. 268. 231. 237. 226.
 197. 168. 284. 249. 262. 207. 239. 204. 190. 258. 185. 216. 222. 263.
 102.  99. 100. 145. 159. 155. 156. 125. 152. 166. 143. 151. 133. 137.
 139. 162. 142. 146. 135. 171. 153. 150. 131. 149. 147. 148. 157. 136.
 124.]
미세먼지농도(㎍/㎥) 196
초미세먼지농도(㎍/㎥) [18. 24. 15. 23. 19. 21. 12. 22. 16. 17. 20. 13. 14. 30. 34. 33. 26. 27.
 29. 25. 28. 31. 32. 36. 38. 41. 42. 37. 35. 40. 39. 59. 64. 61. 68. 57.
 56. 51. 53. 47. 62. 63. 55. 69. 49. 58. 60. 52. 54. 50. 48. 11. 10.  9.
  8.  7. 46. 66. 44. 45. 43.  5.  6.  3.  2.  4.  1. 67. 75. 65. 71. 72.
 70. nan 76.]
초미세먼지농도(㎍/㎥) 74

In [9]:
uni_df(wed)

지점 [400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 421 423 424 425 509 510 889]
지점 27
지점명 ['강남' '서초' '강동' '송파' '강서' '양천' '도봉' '노원' '동대문' '중랑' '기상청' '마포' '서대문' '광진'
 '성북' '용산' '은평' '금천' '한강' '중구' '성동' '구로' '강북*' '남현' '관악' '영등포' '현충원']
지점명 27
일시 ['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09' '2024-01-10'
 '2024-01-11' '2024-01-12' '2024-01-13' '2024-01-14' '2024-01-15'
 '2024-01-16' '2024-01-17' '2024-01-18' '2024-01-19' '2024-01-20'
 '2024-01-21' '2024-01-22' '2024-01-23' '2024-01-24' '2024-01-25'
 '2024-01-26' '2024-01-27' '2024-01-28' '2024-01-29' '2024-01-30'
 '2024-01-31' '2024-02-01' '2024-02-02' '2024-02-03' '2024-02-04'
 '2024-02-05' '2024-02-06' '2024-02-07' '2024-02-08' '2024-02-09'
 '2024-02-10' '2024-02-11' '2024-02-12' '2024-02-13' '2024-02-14'
 '2024-02-15' '2024-02-16' '2024-02-17' '2024-02-18' '2024-02-19'
 '2024-02-20' '2024-02-21' '2024-02-22' '2024-02-23' '2024-02-24'
 '2024-02-25' '2024-02-26' '2024-02-27' '2024-02-28' '2024-02-29'
 '2024-03-01' '2024-03-02' '2024-03-03' '2024-03-04' '2024-03-05'
 '2024-03-06' '2024-03-07' '2024-03-08' '2024-03-09' '2024-03-10'
 '2024-03-11' '2024-03-12' '2024-03-13' '2024-03-14' '2024-03-15'
 '2024-03-16' '2024-03-17' '2024-03-18' '2024-03-19' '2024-03-20'
 '2024-03-21' '2024-03-22' '2024-03-23' '2024-03-24' '2024-03-25'
 '2024-03-26' '2024-03-27' '2024-03-28' '2024-03-29' '2024-03-30'
 '2024-03-31' '2024-04-01' '2024-04-02' '2024-04-03' '2024-04-04'
 '2024-04-05' '2024-04-06' '2024-04-07' '2024-04-08' '2024-04-09'
 '2024-04-10' '2024-04-11' '2024-04-12' '2024-04-13' '2024-04-14'
 '2024-04-15' '2024-04-16' '2024-04-17' '2024-04-18' '2024-04-19'
 '2024-04-20' '2024-04-21' '2024-04-22' '2024-04-23' '2024-04-24'
 '2024-04-25' '2024-04-26' '2024-04-27' '2024-04-28' '2024-04-29'
 '2024-04-30' '2024-05-01' '2024-05-02' '2024-05-03' '2024-05-04'
 '2024-05-05' '2024-05-06' '2024-05-07' '2024-05-08' '2024-05-09'
 '2024-05-10' '2024-05-11' '2024-05-12' '2024-05-13' '2024-05-14'
 '2024-05-15' '2024-05-16' '2024-05-17' '2024-05-18' '2024-05-19'
 '2024-05-20' '2024-05-21' '2024-05-22' '2024-05-23' '2024-05-24'
 '2024-05-25' '2024-05-26' '2024-05-27' '2024-05-28' '2024-05-29'
 '2024-05-30' '2024-05-31' '2024-06-01' '2024-06-02' '2024-06-03'
 '2024-06-04' '2024-06-05' '2024-06-06' '2024-06-07' '2024-06-08'
 '2024-06-09' '2024-06-10' '2024-06-11' '2024-06-12' '2024-06-13'
 '2024-06-14' '2024-06-15' '2024-06-16' '2024-06-17' '2024-06-18'
 '2024-06-19' '2024-06-20' '2024-06-21' '2024-06-22' '2024-06-23'
 '2024-06-24' '2024-06-25' '2024-06-26' '2024-06-27' '2024-06-28'
 '2024-06-29' '2024-06-30' '2024-07-01' '2024-07-02' '2024-07-03'
 '2024-07-04' '2024-07-05' '2024-07-06' '2024-07-07' '2024-07-08'
 '2024-07-09' '2024-07-10' '2024-07-11' '2024-07-12' '2024-07-13'
 '2024-07-14' '2024-07-15' '2024-07-16' '2024-07-17' '2024-07-18'
 '2024-07-19' '2024-07-20' '2024-07-21' '2024-07-22' '2024-07-23'
 '2024-07-24' '2024-07-25' '2024-07-26' '2024-07-27' '2024-07-28'
 '2024-07-29' '2024-07-30' '2024-07-31' '2024-08-01' '2024-08-02'
 '2024-08-03' '2024-08-04' '2024-08-05' '2024-08-06' '2024-08-07'
 '2024-08-08' '2024-08-09' '2024-08-10' '2024-08-11' '2024-08-12'
 '2024-08-13' '2024-08-14' '2024-08-15' '2024-08-16' '2024-08-17'
 '2024-08-18' '2024-08-19' '2024-08-20' '2024-08-21' '2024-08-22'
 '2024-08-23' '2024-08-24' '2024-08-25' '2024-08-26' '2024-08-27'
 '2024-08-28' '2024-08-29' '2024-08-30' '2024-08-31' '2024-09-01'
 '2024-09-02' '2024-09-03' '2024-09-04' '2024-09-05' '2024-09-06'
 '2024-09-07' '2024-09-08' '2024-09-09' '2024-09-10' '2024-09-11'
 '2024-09-12' '2024-09-13' '2024-09-14' '2024-09-15' '2024-09-16'
 '2024-09-17' '2024-09-18' '2024-09-19' '2024-09-20' '2024-09-21'
 '2024-09-22' '2024-09-23' '2024-09-24' '2024-09-25' '2024-09-26'
 '2024-09-27' '2024-09-28' '2024-09-29' '2024-09-30' '2024-10-01'
 '2024-10-02' '2024-10-03' '2024-10-04' '2024-10-05' '2024-10-06'
 '2024-10-07' '2024-10-08' '2024-10-09' '2024-10-10' '2024-10-11'
 '2024-10-12' '2024-10-13' '2024-10-14' '2024-10-15' '2024-10-16'
 '2024-10-17' '2024-10-18' '2024-10-19' '2024-10-20' '2024-10-21'
 '2024-10-22' '2024-10-23' '2024-10-24' '2024-10-25' '2024-10-26'
 '2024-10-27' '2024-10-28' '2024-10-29' '2024-10-30' '2024-10-31'
 '2024-11-01' '2024-11-02' '2024-11-03' '2024-11-04' '2024-11-05'
 '2024-11-06' '2024-11-07' '2024-11-08' '2024-11-09' '2024-11-10'
 '2024-11-11' '2024-11-12' '2024-11-13' '2024-11-14' '2024-11-15'
 '2024-11-16' '2024-11-17' '2024-11-18' '2024-11-19' '2024-11-20'
 '2024-11-21' '2024-11-22' '2024-11-23' '2024-11-24' '2024-11-25'
 '2024-11-26' '2024-11-27' '2024-11-28' '2024-11-29' '2024-11-30'
 '2024-12-01' '2024-12-02' '2024-12-03' '2024-12-04' '2024-12-05'
 '2024-12-06' '2024-12-07' '2024-12-08' '2024-12-09' '2024-12-10'
 '2024-12-11' '2024-12-12' '2024-12-13' '2024-12-14' '2024-12-15'
 '2024-12-16' '2024-12-17' '2024-12-18' '2024-12-19' '2024-12-20'
 '2024-12-21' '2024-12-22' '2024-12-23' '2024-12-24' '2024-12-25'
 '2024-12-26' '2024-12-27' '2024-12-28' '2024-12-29' '2024-12-30'
 '2024-12-31']
일시 366
평균기온(°C) [  3.7   3.6   2.2   2.    5.5   1.6  -3.1  -3.7  -0.4   0.2   1.9   2.3
   1.    0.   -2.2  -1.8   0.6   5.1   6.    3.9   2.6  -7.6 -10.8  -7.
  -4.   -1.1   0.1  -0.5  -0.2   5.    3.8   4.8   7.6   2.9   1.5   1.2
   1.3   1.7   1.8   8.2  12.8   5.7   3.4   4.7   6.3   9.7   2.4   0.7
   2.7   3.3   5.9   7.3   5.6  -3.    6.1   8.5   7.    3.5   6.8   7.1
   6.9   8.7   9.2  11.3   9.8   8.3   7.4  10.6  13.6  15.8  11.1   7.8
  10.7   8.4   9.5  11.4  12.5  15.4  15.6  14.1  13.3  15.2  16.8  16.
  14.4  15.9  17.6  19.4  20.7  16.2  14.2  15.5  17.9  18.2  14.9  17.7
  19.3  18.1  18.5  20.5  21.1  19.   18.8  18.9  19.5  21.5  14.5  13.8
  18.6  17.5  17.4  13.1  21.   22.   20.3  22.8  21.6  21.8  19.8  20.6
  21.9  21.3  23.4  24.2  24.5  24.   23.5  25.4  26.   26.9  27.4  24.6
  24.9  25.   29.   28.9  28.1  24.1  25.5  25.3  25.7  26.7  26.6  24.3
  26.8  23.7  27.6  25.8  26.1  26.2  28.5  28.8  27.   26.5  24.7  27.5
  27.2  28.2  29.1  28.6  30.   29.5  30.1  30.9  30.5  31.4  32.5  29.7
  29.4  30.3  30.6  31.3  31.   31.1  32.   28.7  28.3  26.3  25.1  23.9
  27.3  29.8  26.4  28.   30.2  29.6  24.8  19.9  20.8  23.8  23.   16.3
  16.4  17.1  15.7  18.   17.8  19.2  18.3  12.7  14.3  10.9   8.6   7.7
   9.3  11.9  14.   14.8  16.9   4.1   9.9   7.5  10.5   6.7   3.2   3.
   0.8   0.4   0.3  -2.5  -1.4   0.9  -0.3  -2.7   nan   0.5  -1.7  -2.1
   1.4  -3.2  -3.9  -0.1  -2.3 -10.5  -6.9  -0.7   1.1   5.4   9.6   5.3
   7.2   4.2   8.9   9.1   9.   10.4   8.   15.3  20.   13.9  15.1  17.2
  18.7  13.5  14.7  18.4  12.4  21.2  19.7  20.4  22.5  23.2  23.3  20.1
  25.2  25.9  24.4  23.1  27.1  27.7  28.4  29.2  27.9  29.9  31.2  27.8
  22.7  16.6  19.1  13.4  14.6  16.5  17.3   8.1  12.3  15.    9.4   6.2
   6.5   3.1   2.8  -2.8  -3.6  -1.2   2.1   4.5  -7.3 -10.3  -7.1  -4.4
  -1.5  12.1   4.4   5.2  -2.9   4.3   2.5   6.4  10.3  10.1  12.9  13.2
  22.1  21.4  19.6  20.2  20.9  29.3  30.7  22.3  22.9  22.4  16.7  17.
  12.6  10.2  -3.3   4.   -0.9  -7.8 -10.9  -7.2  -3.8   4.9   5.8  -3.4
   6.6  11.6   7.9  16.1  13.7  21.7  25.6  30.8  32.4  31.6  31.9  -2.6
  -1.3  -2.   -0.6  -4.3  -0.8  -1.6   4.6  11.   11.5  23.6  31.7  30.4
  12.2  -1.   -7.9  -4.1   8.8  13.   31.5  31.8  -2.4  -1.9  -5.1  -8.2
 -11.5  -5.3  10.   11.7  12.   22.6  11.8  -4.5  -3.5  -5.6  -8.  -11.2
  -7.7  -6.7  -4.7  -5.   -8.3 -11.3  -7.4  11.2 -11.   -4.2  22.2  10.8
 -10.7 -13.6  -9.5  -6.3  -5.4  -4.9  -4.6  -8.9 -11.7  -5.2  -9.2 -12.1
  -8.5  -6.   -4.8  -9.1 -12.   -8.4 -11.1  32.2  32.6  -6.6  -6.8  -5.8
  -8.8  -5.9  -6.4  -6.2 -13.9 -10.   -8.6  -7.5 -11.9  -6.1  -5.7  32.7
 -10.6]
평균기온(°C) 432
최저기온(°C) [ -0.9   1.6   0.5  -2.6   2.2  -0.8  -6.9  -8.5  -1.7  -3.   -2.4  -2.5
  -5.   -6.7   1.7   4.7  -1.5 -11.1 -12.9 -10.1  -6.5  -4.6  -4.3  -5.4
  -4.5   0.2   0.7  -1.    3.6   0.3  -1.2  -3.4  -2.8  -2.7   8.1   1.8
  -1.4   0.    5.3   4.2  -0.5   1.    4.1   1.4  -5.9  -6.8   6.1   3.4
   2.7   0.6  -2.    4.6   2.5   2.6   3.9   6.6   2.    5.    9.9   8.
   7.4   2.9   8.7   5.5   3.1  12.9  12.3  10.2   7.7   6.8  10.1  11.6
  10.5  12.6  10.7  10.6  12.   11.7   9.7  10.   13.2  13.5  15.4  13.6
  11.3  11.4  11.2  17.3  15.9  14.8  13.4  11.   12.7  15.5  13.7  12.4
   9.4  10.3  12.5  13.   11.1   7.6  13.9  15.3  17.5  17.1  17.2  17.
  19.5  17.7  15.2  14.3  14.7  16.6  16.7  18.   15.7  19.3  18.3  17.6
  18.7  21.8  18.6  19.8  21.2  21.3  20.   18.9  20.4  22.3  22.   22.1
  21.1  19.7  23.   21.7  24.2  23.9  21.4  23.1  22.4  23.4  22.2  23.3
  25.   24.5  24.   23.5  23.8  24.9  25.7  25.8  25.4  24.7  26.8  27.5
  27.4  26.9  27.   27.8  28.7  26.7  24.1  25.2  24.8  26.   27.2  27.6
  26.5  26.6  25.9  25.3  22.5  24.4  22.6  23.2  24.3  20.9  25.1  22.8
  25.5  21.9  26.1  17.9  11.8  14.5  13.3  15.8  14.   14.6  16.4  13.1
  11.5   9.6  14.4  10.8  10.4  12.2   6.2   8.6   0.1   2.1   6.    0.9
  -0.2  -1.1   0.8  -0.6  -0.3  -3.8  -2.9  -3.9  -3.5  -4.7  -6.   -2.3
  -3.6   nan  -5.2  -4.2   1.9   0.4  -3.3   2.4  -9.1  -3.2  -1.9 -10.7
 -12.6 -10.   -7.8  -6.6  -4.   -5.6  -1.6   1.2  -8.2  -1.3   6.3  -0.7
   4.8   3.3   5.7   3.5   9.5   8.5   7.1   8.2   5.4  12.1   6.9   5.8
   9.3  14.9  12.8   9.8  16.9  10.9   7.5  16.3  16.1  15.6  14.2  16.8
  20.2  20.6  18.2  18.1  21.6  20.5  19.   18.5  19.1  20.3  23.6  23.7
  20.7  22.9  24.6  27.1  25.6  26.4  26.3  26.2  22.7  21.   17.8   9.1
   3.7   9.    8.3  11.9  -0.4   3.   -2.1  -3.7  -5.8  -5.1  -7.6  -9.3
  -1.8  -6.1  -7.1   1.1   4.    1.5 -11.2 -13.1 -10.6  -9.2  -7.3  -4.8
  -5.5  -4.4  -3.1  -2.2  -0.1   3.8   1.3  -6.3  -7.    3.2   5.9   2.3
   6.5   7.   16.2  15.1   7.2  16.   18.8  17.4  16.5  20.1  19.9  19.4
  21.5  28.4  27.3  18.4   4.5  -4.9   5.1 -11.3 -13.  -10.3   4.3   4.4
  -6.4   6.7   2.8   5.2   8.4  13.8   7.8   7.9  20.8  28.   28.1  27.9
  28.8  19.2  14.1   8.9  -5.7  -6.2  -7.5  -9.9  -4.1  -7.4 -11.  -10.2
  -9.7   4.9   9.2   5.6  19.6  28.2  -7.7  -8.  -12.8  -7.9   8.8  28.6
  27.7  15.    6.4  -8.1  -8.4 -12.  -14.1 -11.7 -11.8  -9.5  -7.2   7.3
  -9.4  -8.6  -9.  -13.3  -8.8 -10.9 -11.5 -13.8  -8.7  -5.3  -8.9  -8.3
 -13.7 -10.8  28.3 -13.2 -10.5 -13.9 -16.1 -12.2 -12.5 -14.3 -11.6  28.5
 -12.4 -14.4 -15.   -9.6 -10.4  29.  -16.  -14.2 -11.9  -9.8  29.6  28.9]
최저기온(°C) 431
최고기온(°C) [  7.1   4.8   5.    5.3  10.2   5.7   0.    0.7   0.5   4.9   5.8   6.3
   3.5   1.6   4.7   1.9  10.4   9.8   6.    5.2  -1.4  -7.5  -3.2  -0.2
   4.4   5.5   3.9   8.3  11.4   8.5   8.6   9.1  12.    4.3   6.6   7.5
   6.7  11.2  15.2  18.9  12.1  10.5  12.4   2.2   7.2   7.   10.8  10.9
   1.4   5.1   9.2  12.3  11.7   7.7  11.8  10.   13.   16.1  15.3  19.1
  13.2  14.9  11.9  12.2  17.1  18.5  23.5  14.5  12.6  17.5  17.   17.8
  19.9  25.2  18.   20.7  19.6  24.1  22.9  21.3  21.4  25.   28.   29.8
  22.6  26.3  25.8  22.   25.1  24.5  19.   22.4  26.6  27.4  29.5  26.4
  23.4  24.6  28.9  29.7  20.9  16.3  15.7  23.1  25.5  23.6  25.9  26.2
  21.1  28.1  29.4  27.5  25.6  24.2  27.1  28.8  25.7  27.2  26.9  27.8
  29.3  30.2  31.7  32.1  29.2  32.2  33.   33.5  33.7  34.2  29.1  31.
  31.5  34.   36.9  35.8  34.6  26.7  29.6  31.8  30.8  32.9  33.2  25.4
  31.9  24.9  33.6  30.3  34.3  33.3  30.9  27.3  32.5  34.7  34.9  33.9
  35.1  34.5  36.4  38.   34.4  35.   35.2  35.7  37.3  36.8  36.3  36.1
  36.7  37.2  33.4  32.8  32.3  33.8  32.6  31.1  35.4  31.2  21.   24.4
  18.4  21.6  24.   24.3  23.3  21.7  19.3  22.3  17.2  20.   24.7  20.2
  21.5  19.8  23.2  20.3  13.7  20.5  17.4  15.5  14.3  14.2  16.6  13.4
   3.    6.1  14.1   6.9   9.3   8.    5.9   3.4   5.6   4.1   0.6   4.5
   2.5   nan   1.3  10.6  -0.4   1.    1.1   4.    9.6  -1.8  -7.4  -3.8
   3.6   7.8  11.1   6.4   7.9  15.4  18.8  11.6  12.5   2.4   6.2  10.1
   1.2  15.9  15.   16.8  18.2  17.6  19.5  20.6  20.1  25.3  18.3  26.
  28.3  29.9  15.6  22.7  26.5  28.4  26.8  27.6  24.8  26.1  30.7  28.7
  33.1  36.5  35.6  30.6  27.7  31.3  30.4  31.6  30.5  30.   34.1  34.8
  35.9  35.5  35.3  32.   27.   32.4  27.9  28.5  28.6  28.2  23.7  23.8
  23.9  22.5  19.2  21.8  17.7  19.7  22.1  18.7  14.8  14.4  19.4  20.8
   7.3  13.1  15.8   2.9  14.    3.8   7.6   2.7   0.1   3.7   2.1   6.8
   6.5   4.2   1.5   0.8   5.4   4.6   9.5   0.2   1.8   2.3   9.4   8.9
  -1.7  -6.7  -2.3   8.1   8.4  10.7  14.6  18.1   8.2  10.3   9.   11.5
  16.7  23.   18.6  21.2  29.   20.4  32.7  30.1  21.9  22.8  16.9  16.4
  13.9  15.1  11.3  13.3  12.9   2.8   1.7   0.4  -1.   -8.2  -3.6   3.3
   8.8   7.4  14.7   8.7   9.7  17.3  31.4  38.1  37.   11.   13.5   3.1
   0.3  -0.7  -2.1  -7.   -3.    0.9  12.7   9.9  16.   36.6  36.   37.1
  17.9  12.8  -0.6  -7.3  -3.3   3.2   2.   16.5   2.6  16.2  22.2  -0.1
  -0.3  -8.   37.4  36.2  -1.9  -8.5  -3.5  13.6  -8.4  -2.4  -4.4 -10.2
  -5.4  -1.5  -0.5  -0.9  -1.1  -2.9  13.8  -3.1  -4.3  -1.6  -2.7  -9.1
  -4.5  -2.   -0.8  -8.9  -4.   -7.6  -3.4  -4.1 -10.4  -5.6  -2.2  -7.9
  -2.8  -8.1  -8.7  -1.2  -7.2  37.5]
최고기온(°C) 437
일강수량(mm) [  0.    0.5   1.5   2.5   9.    1.    4.   16.    7.   19.5   7.5   2.
  13.    6.5  15.    3.    3.5  14.5  37.   10.5  23.   26.5  17.   26.
  10.   30.   59.5  15.5   8.5  11.   20.5 122.5  19.   47.    6.   14.
  16.5  80.5  39.   35.5  22.   22.5  54.   11.5  79.   28.   36.   21.
  21.5   9.5   5.5   8.   33.5  24.5  29.   51.5   5.  117.   41.   12.
  31.5  32.5  32.   20.   13.5  52.   64.5  25.   28.5   4.5  23.5  18.5
  54.5 100.  125.   43.   44.5  18.   66.   33.   24.   27.5  55.  115.5
  17.5  25.5  12.5  31.   71.   72.5  57.5 123.   58.   99.5  43.5  35.
  57.  127.   73.   52.5  60.   42.5  36.5  65.5  89.5 130.5  48.5   nan
  29.5  51.   49.5  37.5  39.5  41.5  34.   40.   66.5 137.  114.   56.
  48.   38.   60.5 112.5 124.   50.   34.5  30.5  62.5 103.  120.   55.5
 141.   38.5  46.5  56.5  77.   78.5  42.   59.   98.5 119.5  79.5  47.5
  45.5  58.5  70.5  46.   44.   68.  131.  113.5  27.  117.5  40.5  86.5
 124.5 131.5  45.   65.  133.5  76.5 118.5  75.5 126.  121.   69.5  81.5
  64.  104.5 136.   70.   53.  128.5 118.   62.  129.5]
일강수량(mm) 176

In [52]:
pol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18200 entries, 0 to 18199
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   측정일시          18200 non-null  int64
 1   측정소명          18200 non-null  object
 2   이산화질소농도(ppm)  18187 non-null  float64
 3   오존농도(ppm)     18189 non-null  float64
 4   일산화탄소농도(ppm)  18179 non-null  float64
 5   아황산가스농도(ppm)  18189 non-null  float64
 6   미세먼지농도(㎍/㎥)   18189 non-null  float64
 7   초미세먼지농도(㎍/㎥)  18190 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.1+ MB

In [53]:
wed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9858 entries, 0 to 9857
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   지점        9858 non-null   int64
 1   지점명       9858 non-null   object
 2   일시        9858 non-null   object
 3   평균기온(°C)  9795 non-null   float64
 4   최저기온(°C)  9798 non-null   float64
 5   최고기온(°C)  9798 non-null   float64
 6   일강수량(mm)  9836 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 539.2+ KB

In [59]:
gu_map = {
    '강남': '강남구',
    '강동': '강동구',
    '강북*': '강북구',
    '강서': '강서구',
    '관악': '관악구',
    '광진': '광진구',
    '구로': '구로구',
    '금천': '금천구',
    '노원': '노원구',
    '도봉': '도봉구',
    '동대문': '동대문구',
    '현충원': '동작구',
    '마포': '마포구',
    '서대문': '서대문구',
    '서초': '서초구',
    '성동': '성동구',
    '성북': '성북구',
    '송파': '송파구',
    '양천': '양천구',
    '영등포': '영등포구',
    '용산': '용산구',
    '은평': '은평구',
    '기상청': '종로구',
    '중구': '중구',
    '중랑': '중랑구'
}

In [60]:
wed['자치구'] = wed['지점명'].map(gu_map)

In [61]:
wed = wed.dropna(subset=['자치구'])

In [62]:
wed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9126 entries, 0 to 9857
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   지점        9126 non-null   int64
 1   지점명       9126 non-null   object
 2   일시        9126 non-null   object
 3   평균기온(°C)  9067 non-null   float64
 4   최저기온(°C)  9068 non-null   float64
 5   최고기온(°C)  9068 non-null   float64
 6   일강수량(mm)  9104 non-null   float64
 7   자치구       9126 non-null   object
dtypes: float64(4), int64(1), object(3)
memory usage: 641.7+ KB

In [63]:
wed.head()

    지점 지점명          일시  평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)  자치구
0  400  강남  2024-01-01       3.7      -0.9       7.1       0.0  강남구
1  400  강남  2024-01-02       3.6       1.6       4.8       0.0  강남구
2  400  강남  2024-01-03       2.2       0.5       5.0       0.5  강남구
3  400  강남  2024-01-04       2.0      -2.6       5.3       0.0  강남구
4  400  강남  2024-01-05       5.5       2.2      10.2       0.0  강남구

In [64]:
print(wed.columns)

Index(['지점', '지점명', '일시', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '일강수량(mm)',
       '자치구'],
      dtype='object')

In [65]:
wed = wed.drop(columns=['지점', '지점명'])

In [66]:
# 서울시 25개 자치구 리스트
valid_gu_list = [
    '강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구',
    '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구',
    '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구',
    '종로구', '중구', '중랑구'
]

# 특정 컬럼에서 자치구가 아닌 항목 제거 (예: '자치구' 컬럼이라고 가정)
pol = pol[pol['측정소명'].isin(valid_gu_list)]

In [67]:
wed['일자'] = pd.to_datetime(wed['일시'])
pol['일자'] = pd.to_datetime(pol['측정일시'].astype(str), format='%Y%m%d')

In [68]:
wed = wed.drop(columns=['일시'])
pol = pol.drop(columns=['측정일시'])

In [69]:
pol.head()

,측정소명,이산화질소농도(ppm),오존농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),미세먼지농도(㎍/㎥),초미세먼지농도(㎍/㎥),일자
0,강남구,0.0280,0.0130,0.65,0.0028,23.0,18.0,2024-01-01
2,강동구,0.0305,0.0116,0.92,0.0020,20.0,15.0,2024-01-01
4,강북구,0.0243,0.0157,0.71,0.0025,19.0,15.0,2024-01-01
5,강서구,0.0354,0.0123,0.92,0.0033,29.0,19.0,2024-01-01
7,관악구,0.0332,0.0115,0.87,0.0027,33.0,24.0,2024-01-01

In [70]:
wed.head()

   평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)  자치구         일자
0       3.7      -0.9       7.1       0.0  강남구 2024-01-01
1       3.6       1.6       4.8       0.0  강남구 2024-01-02
2       2.2       0.5       5.0       0.5  강남구 2024-01-03
3       2.0      -2.6       5.3       0.0  강남구 2024-01-04
4       5.5       2.2      10.2       0.0  강남구 2024-01-05

In [77]:
# '측정소명'과 '일자' 기준으로, wed의 전체 날씨 데이터 컬럼과 left join
forcast = wed.merge(pol, how='left', left_on=['자치구', '일자'], right_on=['측정소명', '일자'])

In [78]:
# 자치구가 NaN인 경우 측정소명으로 채움
forcast['자치구'] = forcast['자치구'].fillna(forcast['측정소명'])

# 측정소명 컬럼 제거
forcast = forcast.drop(columns=['측정소명'])

In [79]:
forcast = forcast[[
    '일자', '자치구',
    '평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '일강수량(mm)',
    '이산화질소농도(ppm)', '오존농도(ppm)', '일산화탄소농도(ppm)',
    '아황산가스농도(ppm)', '미세먼지농도(㎍/㎥)', '초미세먼지농도(㎍/㎥)'
]]

In [80]:
forcast.head()

,일자,자치구,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),이산화질소농도(ppm),오존농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),미세먼지농도(㎍/㎥),초미세먼지농도(㎍/㎥)
0,2024-01-01,강남구,3.7,-0.9,7.1,0.0,0.0280,0.0130,0.65,0.0028,23.0,18.0
1,2024-01-02,강남구,3.6,1.6,4.8,0.0,0.0241,0.0237,0.47,0.0028,42.0,30.0
2,2024-01-03,강남구,2.2,0.5,5.0,0.5,0.0341,0.0134,0.51,0.0030,43.0,30.0
3,2024-01-04,강남구,2.0,-2.6,5.3,0.0,0.0341,0.0139,0.63,0.0032,53.0,36.0
4,2024-01-05,강남구,5.5,2.2,10.2,0.0,0.0308,0.0233,0.69,0.0033,83.0,59.0

In [86]:
pol.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9100 entries, 0 to 18192
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   측정소명          9100 non-null   object
 1   이산화질소농도(ppm)  9092 non-null   float64
 2   오존농도(ppm)     9092 non-null   float64
 3   일산화탄소농도(ppm)  9092 non-null   float64
 4   아황산가스농도(ppm)  9092 non-null   float64
 5   미세먼지농도(㎍/㎥)   9090 non-null   float64
 6   초미세먼지농도(㎍/㎥)  9091 non-null   float64
 7   일자            9100 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 639.8+ KB

In [82]:
forcast.to_csv('forcast.csv', index=False)

In [83]:
forcast.duplicated(subset=['일자', '자치구']).sum()

np.int64(0)

In [84]:
forcast[['일자', '자치구']].isna().sum()

일자     0
자치구    0
dtype: int64