In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 파일 불러오기
wed = pd.read_csv('forcast.csv')
veh = pd.read_csv('final_transformed.csv')

In [3]:
wed.head()

,일자,자치구,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),이산화질소농도(ppm),오존농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),미세먼지농도(㎍/㎥),초미세먼지농도(㎍/㎥)
0,2024-01-01,강남구,3.7,-0.9,7.1,0.0,0.0280,0.0130,0.65,0.0028,23.0,18.0
1,2024-01-02,강남구,3.6,1.6,4.8,0.0,0.0241,0.0237,0.47,0.0028,42.0,30.0
2,2024-01-03,강남구,2.2,0.5,5.0,0.5,0.0341,0.0134,0.51,0.0030,43.0,30.0
3,2024-01-04,강남구,2.0,-2.6,5.3,0.0,0.0341,0.0139,0.63,0.0032,53.0,36.0
4,2024-01-05,강남구,5.5,2.2,10.2,0.0,0.0308,0.0233,0.69,0.0033,83.0,59.0

In [4]:
veh.head()

           일자  자치구  총사용수(B)  총사용수(S)
0  2024-01-01  강남구     1319    95566
1  2024-01-01  강동구     1855    33742
2  2024-01-01  강북구      731    22887
3  2024-01-01  강서구     5668    78185
4  2024-01-01  관악구     1438    64662

In [5]:
# '측정소명'과 '일자' 기준으로, wed의 전체 날씨 데이터 컬럼과 left join
final_merge = veh.merge(wed, how='left', left_on=['자치구', '일자'], right_on=['자치구', '일자'])

In [6]:
final_merge.head()

,일자,자치구,총사용수(B),총사용수(S),평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),이산화질소농도(ppm),오존농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),미세먼지농도(㎍/㎥),초미세먼지농도(㎍/㎥)
0,2024-01-01,강남구,1319,95566,3.7,-0.9,7.1,0.0,0.0280,0.0130,0.65,0.0028,23.0,18.0
1,2024-01-01,강동구,1855,33742,2.9,-1.1,6.8,0.0,0.0305,0.0116,0.92,0.0020,20.0,15.0
2,2024-01-01,강북구,731,22887,2.6,-1.4,6.5,0.0,0.0243,0.0157,0.71,0.0025,19.0,15.0
3,2024-01-01,강서구,5668,78185,3.5,-1.5,7.2,0.0,0.0354,0.0123,0.92,0.0033,29.0,19.0
4,2024-01-01,관악구,1438,64662,2.0,-1.3,5.6,0.0,0.0332,0.0115,0.87,0.0027,33.0,24.0

In [7]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9150 entries, 0 to 9149
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   일자            9150 non-null   object
 1   자치구           9150 non-null   object
 2   총사용수(B)       9150 non-null   int64
 3   총사용수(S)       9150 non-null   int64
 4   평균기온(°C)      9067 non-null   float64
 5   최저기온(°C)      9068 non-null   float64
 6   최고기온(°C)      9068 non-null   float64
 7   일강수량(mm)      9104 non-null   float64
 8   이산화질소농도(ppm)  9068 non-null   float64
 9   오존농도(ppm)     9068 non-null   float64
 10  일산화탄소농도(ppm)  9068 non-null   float64
 11  아황산가스농도(ppm)  9068 non-null   float64
 12  미세먼지농도(㎍/㎥)   9066 non-null   float64
 13  초미세먼지농도(㎍/㎥)  9067 non-null   float64
dtypes: float64(10), int64(2), object(2)
memory usage: 1000.9+ KB

In [8]:
final_merge.to_csv('final.csv', index=False)